import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import { afterEach, expect, it } from 'vitest';
import { PiHost } from '../src/main/pi/host';import { SettingsService } from '../src/main/pi/settings-service';import { DEFAULT_SHORTCUTS, shortcutMatches } from '../src/shared/settings';
const roots:string[]=[],hosts:PiHost[]=[];
afterEach(()=>{hosts.splice(0).forEach(h=>h.dispose());roots.splice(0).forEach(p=>fs.rmSync(p,{recursive:true,force:true}));});
function setup(){const root=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'desktop-settings-')));roots.push(root);const agent=path.join(root,'agent'),data=path.join(root,'data'),project=path.join(root,'project');fs.mkdirSync(agent);fs.mkdirSync(data);fs.mkdirSync(project);fs.writeFileSync(path.join(data,'pi-desktop.json'),JSON.stringify({agentDir:agent}));const host=new PiHost(data,path.resolve('extensions/desktop-policy/index.mjs'),()=>{},path.join(root,'shared-skills'));hosts.push(host);const service=new SettingsService(host,data,path.resolve('extensions/desktop-policy'));return{root,agent,project,service,host};}
it('preserves unrelated pi settings, validates AI edits, backs up and detects concurrent changes',()=>{const{agent,service}=setup();const file=path.join(agent,'settings.json');fs.writeFileSync(file,JSON.stringify({theme:'my-theme',unknown:{keep:true},retry:{maxRetries:9}}));const snapshot=service.snapshot();service.saveAi({...snapshot.ai,defaultProvider:'test',defaultModel:'one',defaultThinkingLevel:'high'});const result=JSON.parse(fs.readFileSync(file,'utf8'));expect(result).toMatchObject({theme:'my-theme',unknown:{keep:true},retry:{maxRetries:9,enabled:true},defaultThinkingLevel:'high'});expect(fs.readdirSync(agent).some(f=>f.includes('desktop-backup'))).toBe(true);expect(()=>service.saveAi(snapshot.ai)).toThrow('配置已变化');});
it('persists shortcuts and defaults, prevents conflicts, handles modifiers exactly',()=>{const{service}=setup();service.savePreferences({behavior:'steer',shortcuts:{...DEFAULT_SHORTCUTS,search:'Mod+Shift+K'}});expect(service.preferences().behavior).toBe('steer');expect(()=>service.savePreferences({shortcuts:{...DEFAULT_SHORTCUTS,search:'Mod+B'}})).toThrow('冲突');expect(shortcutMatches({key:'K',metaKey:true,ctrlKey:false,shiftKey:true,altKey:false},'Mod+Shift+K')).toBe(true);expect(shortcutMatches({key:'K',metaKey:true,ctrlKey:false,shiftKey:false,altKey:false},'Mod+Shift+K')).toBe(false);});
it('manages scoped resources without overwriting external changes or escaping root',()=>{const{service,project,agent}=setup();service.projectSave({path:project,name:'Project'});service.createResource({kind:'skills',scope:'project',name:'review',text:'---\ndescription: Review code\n---\nRead only',cwd:project});const r=service.snapshot(project).resources.find(r=>r.kind==='skills')!;expect(r.scope).toBe('project');const doc=service.readResource(r.id,project);service.saveResource({...doc,text:doc.text+'\nUpdated',cwd:project});expect(()=>service.saveResource({...doc,text:'stale',cwd:project})).toThrow('其他程序修改');service.toggleResource(r.id,false,project);expect(JSON.parse(fs.readFileSync(path.join(project,'.pi/settings.json'),'utf8')).skills).toContain('-'+r.path);expect(()=>service.createResource({kind:'extensions',scope:'user',name:'../escape',text:'bad'})).toThrow('名称');expect(()=>service.readResource('unknown',project)).toThrow('不存在');fs.symlinkSync(project,path.join(agent,'skills'));expect(()=>service.createResource({kind:'skills',scope:'user',name:'escape',text:'bad'})).toThrow('符号链接');});
it('imports native history once, protects source, rejects corrupted input and retains branches',()=>{const{service,project,root,host}=setup();const file=path.join(root,'source.jsonl');const content=[{type:'session',version:3,id:'external',cwd:project},{type:'message',id:'a',parentId:null,message:{role:'user',content:'hello'}},{type:'message',id:'b',parentId:'a',message:{role:'assistant',content:'A'}},{type:'message',id:'c',parentId:'a',message:{role:'assistant',content:'B'}}].map(e=>JSON.stringify(e)).join('\n')+'\n';fs.writeFileSync(file,content);const first=service.importFile(file);expect(first.duplicate).toBe(false);expect(service.importFile(file)).toEqual({...first,duplicate:true});expect(fs.readFileSync(file,'utf8')).toBe(content);expect(host.index.history(first.key).leaves).toEqual(['b','c']);fs.appendFileSync(file,'broken');expect(()=>service.importFile(file)).toThrow('损坏');});
it('MCP metadata never exposes auth or arguments, toggles preserve secrets and detect stale revisions',()=>{const{service,agent}=setup();const file=path.join(agent,'mcp.json');fs.writeFileSync(file,JSON.stringify({imports:['other'],mcpServers:{demo:{command:'node',args:['--token','SECRET'],env:{TOKEN:'SECRET'},custom:'keep'}}}));const snapshot=service.snapshot();expect(JSON.stringify(snapshot)).not.toContain('SECRET');const row=snapshot.mcp[0];service.mcpSave({name:row.name,scope:row.scope,revision:row.revision,enabled:false});expect(JSON.parse(fs.readFileSync(file,'utf8')).mcpServers.demo).toMatchObject({disabled:true,custom:'keep',env:{TOKEN:'SECRET'}});expect(()=>service.mcpSave({name:row.name,scope:row.scope,revision:row.revision,remove:true})).toThrow('变化');});
it('project removal only removes registration, never project files or CLI sessions',()=>{const{service,project}=setup();fs.writeFileSync(path.join(project,'keep'),'data');service.projectSave({path:project,name:'Mine'});expect(service.snapshot().projects[0].name).toBe('Mine');service.projectSave({path:project,name:'Mine',remove:true});expect(service.preferences().projects).toEqual([]);expect(fs.readFileSync(path.join(project,'keep'),'utf8')).toBe('data');});
it('persists project pinning and sections, preserves them on rename, and restores removed projects',()=>{
 const{service,project}=setup();service.projectSave({path:project,name:'Mine',pinned:true,section:'Work'});
 service.projectSave({path:project,name:'Renamed'});
 expect(service.preferences().projects[0]).toMatchObject({name:'Renamed',pinned:true,section:'Work'});
 service.projectSave({path:project,name:'Renamed',remove:true});expect(service.preferences().hiddenProjects).toContain(project);
 service.projectSave({path:project,name:'Restored'});expect(service.preferences().hiddenProjects).not.toContain(project);
 expect(service.preferences().projects[0].name).toBe('Restored');
});

it('persists session renames as desktop-only display names',()=>{const{service,root}=setup();
 expect(service.preferences().sessionRenames).toEqual({});
 service.savePreferences({sessionRenames:{'key-1':'1111','key-2':'修复登录'}});
 expect(service.preferences().sessionRenames).toMatchObject({'key-1':'1111'});
 expect(()=>service.savePreferences({sessionRenames:{bad:123 as unknown as string}})).toThrow('重命名无效');
 expect(()=>service.savePreferences({unknown:'x'} as never)).toThrow('不支持的设置项');
 const agent=path.join(root,'agent'),data=path.join(root,'data');
 const host=new PiHost(data,path.resolve('extensions/desktop-policy/index.mjs'),()=>{},path.join(root,'shared-skills'));hosts.push(host);
 expect(new SettingsService(host,data,path.resolve('extensions/desktop-policy')).preferences().sessionRenames['key-2']).toBe('修复登录');
});
it('persists auto-archive preferences and validates retention values',()=>{const{service}=setup();expect(service.preferences()).toMatchObject({autoArchive:false,archiveRetentionDays:30});service.savePreferences({autoArchive:true,archiveRetentionDays:90});expect(service.preferences()).toMatchObject({autoArchive:true,archiveRetentionDays:90});expect(()=>service.savePreferences({archiveRetentionDays:45 as never})).toThrow('保留时长');expect(()=>service.savePreferences({autoArchive:'yes' as never})).toThrow('自动归档');expect(()=>service.savePreferences({autoArchive:false,archiveRetentionDays:7})).not.toThrow();expect(service.preferences()).toMatchObject({autoArchive:false,archiveRetentionDays:7});});
it('persists per-session access mode and restores it on re-entry',()=>{const{service}=setup();expect(service.preferences().sessionAccessModes).toEqual({});service.savePreferences({sessionAccessModes:{'session-a':'fullAccess','session-b':'plan'}});expect(service.preferences().sessionAccessModes).toEqual({'session-a':'fullAccess','session-b':'plan'});expect(()=>service.savePreferences({sessionAccessModes:{'session-a':'garbage' as never}})).toThrow('访问模式');service.savePreferences({sessionAccessModes:{'session-a':'autoEdit'}});expect(service.preferences().sessionAccessModes).toEqual({'session-a':'autoEdit'});});
it('persists the chosen thinking level across restarts',()=>{const{root,service}=setup();expect(service.preferences().defaultThinkingLevel).toBe('off');service.savePreferences({defaultThinkingLevel:'high'});expect(service.preferences().defaultThinkingLevel).toBe('high');expect(()=>service.savePreferences({defaultThinkingLevel:'ultra' as never})).toThrow('思考等级');expect(new SettingsService({} as never,path.join(root,'data'),'').preferences().defaultThinkingLevel).toBe('high');});
