import { useEffect, useState } from 'react';
import type { AutomationSnapshot, AutomationTask, SavedWorkflow, WorkflowLaunch, AutomationRun, Schedule } from '../../shared/automation';
import { Icon } from '../replica/Icons';
import { thinkingNames } from './ComposerTools';
import type { ThinkingLevel } from '../../shared/composer';
import './automations.css';
const api=()=>window.localPi!;
const time=(v?:number)=>v?new Date(v).toLocaleString('zh-CN',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}):'—';
const statuses:Record<string,string>={running:'运行中',waiting:'等待审批',succeeded:'已完成',failed:'失败',stopped:'已停止',interrupted:'已中断',skipped:'已跳过'};
const modes=[['plan','计划模式'],['ask','变更前确认'],['autoEdit','自动编辑'],['fullAccess','完全访问']] as const;
const live=(run:AutomationRun)=>['running','waiting'].includes(run.status);
const scheduleLabel=(s:Schedule)=>s.kind==='once'?`仅一次 · ${time(s.at)}`:s.kind==='interval'?`每 ${s.minutes} 分钟`:`Cron · ${s.expression}`;
const localDate=(n:number)=>{if(!Number.isFinite(n))return '';const d=new Date(n);return new Date(n-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
function newTask(cwd=''):AutomationTask{return {id:'',name:'',cwd,prompt:'',args:{},permission:'ask',schedule:{kind:'cron',expression:'0 9 * * *'},enabled:true,runCount:0,updatedAt:0};}
function newWorkflow(cwd=''):SavedWorkflow{return {id:'',name:'',description:'',whenToUse:'',scope:cwd?'project':'global',cwd,parameters:[],steps:[{id:crypto.randomUUID(),name:'第一步',prompt:''}],updatedAt:0};}
function CronFields({expression,onChange}:{expression:string;onChange:(value:string)=>void}) {
 const parts=expression.trim().split(/\s+/),tail=parts.slice(2).join(' ');
 const presets=[['* * *','每天'],['* * 1-5','工作日'],['* * 1','每周一'],['1 * *','每月 1 日'],['1 1 *','每年 1 月 1 日']];
 const preset=presets.some(([v])=>v===tail)&&/^\d+$/.test(parts[0])&&/^\d+$/.test(parts[1])?tail:'custom';
 return <><label>时间规则<select value={preset} onChange={e=>onChange(e.target.value==='custom'?'0 9 * * 0,6':`${parts[0]&&/^\d+$/.test(parts[0])?parts[0]:'0'} ${parts[1]&&/^\d+$/.test(parts[1])?parts[1]:'9'} ${e.target.value}`)}>{presets.map(([v,label])=><option key={v} value={v}>{label}</option>)}<option value="custom">自定义 Cron</option></select></label>{preset==='custom'?<label>Cron 表达式<input aria-label="Cron 表达式" value={expression} onChange={e=>onChange(e.target.value)}/><small>分钟 小时 日 月 星期 · 本机时区</small></label>:<label>本地时间<input required type="time" value={`${parts[1].padStart(2,'0')}:${parts[0].padStart(2,'0')}`} onChange={e=>{if(e.target.value){const [h,m]=e.target.value.split(':');onChange(`${Number(m)} ${Number(h)} ${tail}`);}}}/></label>}</>;
}
export function AutomationsPage({projects,models,onOpenSession}:{projects:string[];models:{id:string;name:string}[];onOpenSession:(key:string)=>void}){
 const [data,setData]=useState<AutomationSnapshot>({tasks:[],workflows:[],runs:[]});
 const [tab,setTab]=useState<'tasks'|'workflows'>(()=>localStorage.getItem('pi-automation-tab')==='workflows'?'workflows':'tasks');
 useEffect(()=>{localStorage.setItem('pi-automation-tab',tab);},[tab]);
 const [task,setTask]=useState<AutomationTask|null>(null),[workflow,setWorkflow]=useState<SavedWorkflow|null>(null);
 const [launch,setLaunch]=useState<WorkflowLaunch|null>(null),[history,setHistory]=useState<{kind:'task'|'workflow'|'all';id:string;name:string}|null>(null);
 const [query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 const [confirmDelete,setConfirmDelete]=useState<{kind:'task'|'workflow';id:string;name:string}|null>(null);
 const [source,setSource]=useState(false);
 async function refresh(){setData(await api().automationSnapshot());}
 useEffect(()=>{let alive=true;const load=()=>void api().automationSnapshot().then(value=>{if(alive){setData(value);setLoading(false);}}).catch(e=>{if(alive){setError(String(e.message||e));setLoading(false);}});load();const off=api().onAutomationChanged(load);return()=>{alive=false;off();};},[]);
 async function action(fn:()=>Promise<unknown>){if(busy)return;setBusy(true);setError('');try{await fn();await refresh();}catch(e){setError(String((e as Error).message||e));}finally{setBusy(false);}}
 const patchTask=(patch:Partial<AutomationTask>)=>setTask(t=>t?{...t,...patch}:t);
 const patchWorkflow=(patch:Partial<SavedWorkflow>)=>setWorkflow(w=>w?{...w,...patch}:w);
 const chooseDir=async(set:(p:string)=>void)=>{const p=await api().pickDirectory();if(p)set(p);};
 const modelSelect=(value:string|undefined,set:(value:string)=>void)=><label>模型<select value={value||''} onChange={e=>set(e.target.value)}><option value="">使用 pi 默认模型</option>{models.map(m=><option value={m.id} key={m.id}>{m.name}</option>)}{value&&!models.some(m=>m.id===value)&&<option value={value}>{value}</option>}</select></label>;
 const permissionSelect=(value:string,set:(v:any)=>void)=><label>访问模式<select value={value} onChange={e=>set(e.target.value)}>{modes.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>;
 const projectSelect=(value:string,set:(p:string)=>void)=><label className="pi-auto__project">项目目录<div><select value={value} onChange={e=>set(e.target.value)}><option value="">选择本地项目</option>{[...new Set([...projects,...(value?[value]:[])])].map(p=><option key={p} value={p}>{p}</option>)}</select><button type="button" onClick={()=>void action(()=>chooseDir(set))}>浏览…</button></div></label>;
 const paramsForm=(w:SavedWorkflow,args:Record<string,string>,set:(a:Record<string,string>)=>void)=><div className="pi-auto__fields">{w.parameters.map(p=><label key={p.name}>{p.name}{p.required?' *':''}<small>{p.description} · {p.type}</small><input placeholder={p.defaultValue||'参数值'} value={args[p.name]??p.defaultValue??''} onChange={e=>set({...args,[p.name]:e.target.value})}/></label>)}</div>;
 const runs=history?data.runs.filter(r=>history.kind==='all'?true:history.kind==='task'?r.taskId===history.id:r.workflowId===history.id):[];
 const back=()=>{setTask(null);setWorkflow(null);setHistory(null);setSource(false);setError('');};
 const finished=(t:AutomationTask)=>!t.nextRunAt||!!t.maxRuns&&t.runCount>=t.maxRuns||!!t.endAt&&t.endAt<=Date.now();
 const allTasks=data.tasks.filter(t=>t.name.toLowerCase().includes(query.toLowerCase())&&(filter==='all'||filter==='active'&&t.enabled||filter==='paused'&&!t.enabled&&!finished(t)||filter==='completed'&&!t.enabled&&finished(t)));
 const allWorkflows=data.workflows.filter(w=>(w.name+' '+w.description).toLowerCase().includes(query.toLowerCase()));
 const title=task?(task.id?'编辑任务':'新建任务'):workflow?(workflow.id?'编辑工作流':'新建工作流'):history?history.name:'自动化';
 return <section className="pi-auto">
  <header className="pi-auto__header"><div>{(task||workflow||history)&&<button className="pi-auto__back" onClick={back}><Icon name="chevron-left" size={14}/>自动化</button>}<h1>{title}</h1><p>{task?'设置指令和时间，让 pi 在本地项目中执行。':workflow?'将常用操作保存为可传参、可重复执行的 pi 工作流。':history?'每次执行的状态、步骤与会话记录。':'把重复工作交给 pi，把时间留给新的想法。'}</p></div>{!(task||workflow||history)&&<div className="pi-auto__buttons"><button onClick={()=>setHistory({kind:'all',id:'',name:'全部运行记录'})}>运行记录</button>{tab==='workflows'&&<button disabled={busy} onClick={()=>void action(async()=>{const w=await api().automationImport();if(w)setWorkflow(w);})}>导入</button>}<button className="pi-auto__primary" onClick={()=>{setError('');tab==='tasks'?setTask(newTask(projects[0])):setWorkflow(newWorkflow(projects[0]));}}><Icon name="plus" size={15}/>{tab==='tasks'?'新建任务':'新建工作流'}</button></div>}</header>
  {error&&<div className="pi-auto__error" role="alert">{error}<button onClick={()=>setError('')} aria-label="关闭错误">×</button></div>}
  {task&&<form className="pi-auto__form" onSubmit={e=>{e.preventDefault();void action(async()=>{await api().automationSaveTask(task);back();});}}>
   <label>任务名称<input required maxLength={100} value={task.name} onChange={e=>patchTask({name:e.target.value})} placeholder="例如：每天检查项目质量"/></label>
   {projectSelect(task.cwd,cwd=>patchTask({cwd}))}
   <label>执行内容<select value={task.workflowId||''} onChange={e=>patchTask({workflowId:e.target.value||undefined,args:{}})}><option value="">任务指令</option>{data.workflows.filter(w=>w.scope==='global'||w.cwd===task.cwd).map(w=><option key={w.id} value={w.id}>工作流 · {w.name}</option>)}</select></label>
   {!task.workflowId?<label>指令<textarea required rows={6} value={task.prompt} onChange={e=>patchTask({prompt:e.target.value})} placeholder="描述要执行的任务、检查范围和期望输出…"/></label>:data.workflows.find(w=>w.id===task.workflowId)&&paramsForm(data.workflows.find(w=>w.id===task.workflowId)!,task.args,args=>patchTask({args}))}
   <div className="pi-auto__fields">{modelSelect(task.model,model=>patchTask({model}))}{permissionSelect(task.permission,permission=>patchTask({permission}))}<label>思考等级<select value={task.thinking||''} onChange={e=>patchTask({thinking:e.target.value as any||undefined})}><option value="">模型默认</option>{['off','minimal','low','medium','high','xhigh','max'].map(v=><option key={v} value={v}>{thinkingNames[v as ThinkingLevel]}</option>)}</select></label></div>
   <fieldset><legend>执行时间</legend><div className="pi-auto__fields"><label>重复<select value={task.schedule.kind} onChange={e=>patchTask({schedule:e.target.value==='once'?{kind:'once',at:Date.now()+3600000}:e.target.value==='interval'?{kind:'interval',minutes:60}:{kind:'cron',expression:'0 9 * * *'}})}><option value="once">仅一次</option><option value="interval">固定间隔</option><option value="cron">每日 / 每周 / 自定义</option></select></label>
    {task.schedule.kind==='once'&&<label>本地日期与时间<input required type="datetime-local" value={localDate(task.schedule.at)} onChange={e=>patchTask({schedule:{kind:'once',at:new Date(e.target.value).getTime()}})}/></label>}
    {task.schedule.kind==='interval'&&<label>间隔（分钟）<input type="number" required min={1} max={525600} value={task.schedule.minutes} onChange={e=>patchTask({schedule:{kind:'interval',minutes:Number(e.target.value)}})}/></label>}
    {task.schedule.kind==='cron'&&<CronFields expression={task.schedule.expression} onChange={expression=>patchTask({schedule:{kind:'cron',expression}})}/>}
   </div><div className="pi-auto__fields"><label>最多执行次数<input type="number" min={1} placeholder="不限制" value={task.maxRuns??''} onChange={e=>patchTask({maxRuns:e.target.value?Number(e.target.value):undefined})}/></label><label>截止时间<input type="datetime-local" value={task.endAt?localDate(task.endAt):''} onChange={e=>patchTask({endAt:e.target.value?new Date(e.target.value).getTime():undefined})}/></label></div></fieldset>
   <label className="pi-auto__check"><input type="checkbox" checked={task.enabled} onChange={e=>patchTask({enabled:e.target.checked})}/>保存后启用调度</label>
   <p className="pi-auto__hint">需要 PI Desktop 窗口保持打开，电脑处于唤醒状态。需要确认的工具会等待你的审批。</p>
   <footer><button type="button" onClick={back}>取消</button><button className="pi-auto__primary" disabled={busy} type="submit">保存任务</button></footer>
  </form>}
  {workflow&&<form className="pi-auto__form" onSubmit={e=>{e.preventDefault();void action(async()=>{await api().automationSaveWorkflow(workflow);back();});}}>
   <div className="pi-auto__tabs"><button type="button" aria-pressed={!source} onClick={()=>setSource(false)}>定义</button><button type="button" aria-pressed={source} onClick={()=>setSource(true)}>查看定义 JSON</button></div>
   {source?<pre className="pi-auto__source">{JSON.stringify(workflow,null,2)}</pre>:<>
   <label>工作流名称<input required maxLength={100} value={workflow.name} onChange={e=>patchWorkflow({name:e.target.value})}/></label>
   <label>描述<textarea rows={2} value={workflow.description} onChange={e=>patchWorkflow({description:e.target.value})}/></label>
   <label>适用场景<input value={workflow.whenToUse} onChange={e=>patchWorkflow({whenToUse:e.target.value})} placeholder="例如：准备提交代码时"/></label>
   <label>保存范围<select value={workflow.scope} onChange={e=>patchWorkflow({scope:e.target.value as any,cwd:workflow.cwd||projects[0]||''})}><option value="project">当前项目</option><option value="global">全局 · 任意项目可用</option></select></label>
   {workflow.scope==='project'&&projectSelect(workflow.cwd,cwd=>patchWorkflow({cwd}))}
   <fieldset><legend>运行参数</legend><p className="pi-auto__hint">在步骤指令中用 {'{{参数名}}'} 引用；运行时填写实际值。</p>
   {workflow.parameters.map((param,index)=><div className="pi-auto__parameter" key={index}><input aria-label="参数名" required placeholder="参数名" value={param.name} onChange={e=>patchWorkflow({parameters:workflow.parameters.map((p,i)=>i===index?{...p,name:e.target.value}:p)})}/><select aria-label="参数类型" value={param.type} onChange={e=>patchWorkflow({parameters:workflow.parameters.map((p,i)=>i===index?{...p,type:e.target.value as any}:p)})}>{['string','number','boolean','json'].map(v=><option key={v}>{v}</option>)}</select><input aria-label="参数说明" placeholder="说明" value={param.description} onChange={e=>patchWorkflow({parameters:workflow.parameters.map((p,i)=>i===index?{...p,description:e.target.value}:p)})}/><input aria-label="默认值" placeholder="默认值" value={param.defaultValue||''} onChange={e=>patchWorkflow({parameters:workflow.parameters.map((p,i)=>i===index?{...p,defaultValue:e.target.value}:p)})}/><label className="pi-auto__check"><input type="checkbox" checked={param.required} onChange={e=>patchWorkflow({parameters:workflow.parameters.map((p,i)=>i===index?{...p,required:e.target.checked}:p)})}/>必填</label><button type="button" aria-label="删除参数" onClick={()=>patchWorkflow({parameters:workflow.parameters.filter((_,i)=>i!==index)})}>×</button></div>)}
   <button type="button" onClick={()=>patchWorkflow({parameters:[...workflow.parameters,{name:'',description:'',type:'string',required:true}]})}>＋ 添加参数</button></fieldset>
   <fieldset><legend>执行步骤</legend><p className="pi-auto__hint">步骤在同一个 pi 会话中依次执行，后续步骤能看到前面的结果；失败时停止。</p>
   {workflow.steps.map((step,index)=><div className="pi-auto__step" key={step.id}><div><span>{index+1}</span><input required aria-label="步骤名称" value={step.name} onChange={e=>patchWorkflow({steps:workflow.steps.map((s,i)=>i===index?{...s,name:e.target.value}:s)})}/><button type="button" disabled={index===0} aria-label="上移步骤" onClick={()=>{const steps=[...workflow.steps];[steps[index-1],steps[index]]=[steps[index],steps[index-1]];patchWorkflow({steps});}}>↑</button><button type="button" disabled={index===workflow.steps.length-1} aria-label="下移步骤" onClick={()=>{const steps=[...workflow.steps];[steps[index+1],steps[index]]=[steps[index],steps[index+1]];patchWorkflow({steps});}}>↓</button><button type="button" disabled={workflow.steps.length===1} aria-label="删除步骤" onClick={()=>patchWorkflow({steps:workflow.steps.filter((_,i)=>i!==index)})}>×</button></div><textarea aria-label="步骤指令" required rows={4} value={step.prompt} onChange={e=>patchWorkflow({steps:workflow.steps.map((s,i)=>i===index?{...s,prompt:e.target.value}:s)})} placeholder="描述该步骤的任务与输出…"/></div>)}
   <button type="button" onClick={()=>patchWorkflow({steps:[...workflow.steps,{id:crypto.randomUUID(),name:`步骤 ${workflow.steps.length+1}`,prompt:''}]})}>＋ 添加步骤</button></fieldset>
   </>}
   <footer><button type="button" onClick={back}>取消</button><button className="pi-auto__primary" disabled={busy} type="submit">保存工作流</button></footer>
  </form>}
  {history&&<div className="pi-auto__history">{!runs.length&&<p className="pi-auto__empty">还没有运行记录，立即运行后会显示在这里。</p>}{runs.map(run=><article key={run.id}><header><span className={`pi-auto__status pi-auto__status--${run.status}`}>{statuses[run.status]}</span><span>{run.name} · {time(run.startedAt)} · {run.trigger==='manual'?'手动运行':'定时触发'}</span><span>{run.endedAt?`${Math.max(0,Math.round((run.endedAt-run.startedAt)/1000))} 秒`:''}</span></header><p className="pi-auto__hint">{run.cwd}</p>{run.error&&<p className="pi-auto__error">{run.error}</p>}<ol>{run.steps.map((step,index)=><li key={index} className={`pi-auto__step-status--${step.status}`}>{step.name}<small>{({pending:'等待',running:'执行中',succeeded:'完成',failed:'失败',stopped:'已停止'})[step.status]}</small></li>)}</ol><div className="pi-auto__buttons">{run.sessionKey&&<button onClick={()=>onOpenSession(run.sessionKey!)}>查看会话{run.status==='waiting'?' / 处理审批':''}</button>}{live(run)&&<button disabled={busy} onClick={()=>void action(()=>api().automationStop(run.id))}>停止</button>}</div></article>)}</div>}
  {!(task||workflow||history)&&<>
   <div className="pi-auto__tabs"><button aria-pressed={tab==='tasks'} onClick={()=>{setTab('tasks');setQuery('');}}>任务 <small>{data.tasks.length}</small></button><button aria-pressed={tab==='workflows'} onClick={()=>{setTab('workflows');setQuery('');}}>工作流 <small>{data.workflows.length}</small></button></div>
   <div className="pi-auto__filters"><input aria-label="搜索自动化" placeholder={tab==='tasks'?'搜索任务…':'搜索工作流…'} value={query} onChange={e=>setQuery(e.target.value)}/>{tab==='tasks'&&<select aria-label="任务状态" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">全部状态</option><option value="active">已启用</option><option value="paused">已暂停</option><option value="completed">已结束</option></select>}<button disabled={busy} onClick={()=>void action(refresh)}><Icon name="refresh" size={14}/>刷新</button></div>
   {loading?<p className="pi-auto__empty">正在读取自动化…</p>:<div className="pi-auto__grid">
    {tab==='tasks'?allTasks.map(t=>{const latest=data.runs.find(r=>r.taskId===t.id);return <article className="pi-auto__card" key={t.id}><header><Icon name="calendar-clock" size={21}/><button role="switch" aria-checked={t.enabled} aria-label={`${t.enabled?'暂停':'启用'} ${t.name}`} className={`pi-auto__switch ${t.enabled?'is-on':''}`} disabled={busy} onClick={()=>void action(()=>api().automationToggle(t.id))}><i/></button></header><button className="pi-auto__card-title" onClick={()=>setTask(structuredClone(t))}>{t.name}</button><p>{t.workflowId?`工作流 · ${data.workflows.find(w=>w.id===t.workflowId)?.name||'已移除'}`:t.prompt}</p><small title={t.cwd}><Icon name="folder" size={13}/>{t.cwd.split('/').pop()}</small><div className="pi-auto__schedule">{scheduleLabel(t.schedule)}<br/>{t.enabled?`下次 ${time(t.nextRunAt)}`:finished(t)?'已结束':'已暂停'} · 已执行 {t.runCount} 次</div>{latest&&<button className="pi-auto__last" onClick={()=>setHistory({kind:'task',id:t.id,name:t.name})}>最近：{statuses[latest.status]} · {time(latest.startedAt)}</button>}<footer><button disabled={busy} onClick={()=>void action(async()=>{await api().automationRunTask(t.id);setHistory({kind:'task',id:t.id,name:t.name});})}>立即运行</button><button onClick={()=>setHistory({kind:'task',id:t.id,name:t.name})}>记录</button><button aria-label={`编辑 ${t.name}`} onClick={()=>setTask(structuredClone(t))}><Icon name="pencil" size={14}/></button><button aria-label={`删除 ${t.name}`} onClick={()=>setConfirmDelete({kind:'task',id:t.id,name:t.name})}><Icon name="trash" size={14}/></button></footer></article>;}):allWorkflows.map(w=><article className="pi-auto__card" key={w.id}><header><Icon name="git-branch" size={21}/><span className="pi-auto__scope">{w.scope==='global'?'全局工作流':w.cwd.split('/').pop()}</span></header><button className="pi-auto__card-title" onClick={()=>setWorkflow(structuredClone(w))}>{w.name}</button><p>{w.description||w.whenToUse||'可复用的 pi 工作流'}</p><small>{w.steps.length} 个步骤 · {w.parameters.length} 个参数</small><footer><button onClick={()=>setLaunch({id:w.id,cwd:w.cwd||projects[0]||'',args:{},permission:'ask'})}>运行</button><button onClick={()=>setHistory({kind:'workflow',id:w.id,name:w.name})}>记录</button><button title="导出工作流" aria-label={`导出 ${w.name}`} onClick={()=>void action(()=>api().automationExport(w.id))}><Icon name="download" size={14}/></button><button aria-label={`复制 ${w.name}`} onClick={()=>setWorkflow({...structuredClone(w),id:'',name:w.name+' 副本'})}><Icon name="plus-square" size={14}/></button><button aria-label={`删除 ${w.name}`} onClick={()=>setConfirmDelete({kind:'workflow',id:w.id,name:w.name})}><Icon name="trash" size={14}/></button></footer></article>)}
   </div>}
   {!loading&&(tab==='tasks'?allTasks:allWorkflows).length===0&&<div className="pi-auto__empty"><Icon name={tab==='tasks'?'calendar-clock':'git-branch'} size={34}/><h2>{query?'没有匹配的结果':tab==='tasks'?'让重复工作按时完成':'把好用的流程保存下来'}</h2><p>{tab==='tasks'?'创建一个任务，设置项目、指令与执行时间。':'添加步骤与参数，一次定义，反复运行。'}</p></div>}
   {!query&&<><h2 className="pi-auto__section-title">从常用场景开始</h2><div className="pi-auto__templates">{[{name:'每日项目巡检',prompt:'检查项目 Git 状态、近期提交和可运行的测试，汇总风险与建议。不要修改文件。',icon:'search' as const},{name:'变更审查',prompt:'审查当前项目的未提交修改，列出可能的缺陷、影响与验证建议。不要修改文件。',icon:'diff' as const},{name:'实现与验证',prompt:'根据需求 {{request}} 检查相关代码并实现修改。',icon:'code' as const}].map((tpl,index)=><button key={tpl.name} onClick={()=>{if(tab==='tasks')setTask({...newTask(projects[0]),name:tpl.name,prompt:index===2?'检查当前项目待办，提出下一步实现计划。':tpl.prompt,permission:'plan'});else setWorkflow({...newWorkflow(projects[0]),name:tpl.name,description:tpl.name,parameters:index===2?[{name:'request',description:'要实现的需求',type:'string',required:true}]:[],steps:[{id:crypto.randomUUID(),name:index===2?'实现需求':'检查项目',prompt:tpl.prompt},{id:crypto.randomUUID(),name:'验证与总结',prompt:'验证上一步结果，运行适用的检查，汇总结论与未解决的问题。'}]});}}><Icon name={tpl.icon} size={19}/><span>{tpl.name}<small>{tab==='tasks'?'创建定时任务':'创建两步工作流'}</small></span><Icon name="plus" size={16}/></button>)}</div></>}
   <p className="pi-auto__notice"><Icon name="info" size={15}/>本地执行：保持客户端窗口打开与电脑唤醒。错过的时间会记录为跳过；退出时未完成的运行标记为中断。</p>
  </>}
  {launch&&<div className="pi-overlay" role="dialog" aria-modal="true" aria-label="运行工作流"><form className="pi-auto__modal" onSubmit={e=>{e.preventDefault();void action(async()=>{const r=await api().automationRunWorkflow(launch);setLaunch(null);setHistory({kind:'workflow',id:launch.id,name:r.name});});}}><h2>运行 · {data.workflows.find(w=>w.id===launch.id)?.name}</h2>{projectSelect(launch.cwd,cwd=>setLaunch({...launch,cwd}))}{data.workflows.find(w=>w.id===launch.id)&&paramsForm(data.workflows.find(w=>w.id===launch.id)!,launch.args,args=>setLaunch({...launch,args}))}{modelSelect(launch.model,model=>setLaunch({...launch,model}))}{permissionSelect(launch.permission,permission=>setLaunch({...launch,permission}))}{error&&<p role="alert" className="pi-auto__error">{error}</p>}<footer><button type="button" onClick={()=>{setLaunch(null);setError('');}}>取消</button><button className="pi-auto__primary" disabled={busy}>开始运行</button></footer></form></div>}
  {confirmDelete&&<div className="pi-overlay" role="dialog" aria-modal="true" aria-label="删除自动化"><div className="pi-auto__modal"><h2>删除“{confirmDelete.name}”？</h2><p>删除定义后，已有运行记录和会话仍保留。</p>{error&&<p className="pi-auto__error">{error}</p>}<footer><button onClick={()=>setConfirmDelete(null)}>取消</button><button disabled={busy} onClick={()=>void action(async()=>{if(confirmDelete.kind==='task')await api().automationDeleteTask(confirmDelete.id);else await api().automationDeleteWorkflow(confirmDelete.id);setConfirmDelete(null);})}>删除</button></footer></div></div>}
 </section>;
}
